### ISSUE TITLE
bool? for boolean

### ISSUE THREAD

**Issue by daonsh** [taoensso/truss#6]
Hi,

Perhaps unrelated to this library itself, but relevant for its use - 

So we have these functions:  vector? string? integer?

I cannot find bool? or boolean?  in the Clojure docs.
Also it'd be helpful to have a link to a list of these kinds of functions that are available, couldn't find one (except for those in the examples).

Thanks

**Comment by ptaoussanis** [comment]
Actually there wasn't a `boolean?` predicate in Clojure until Clojure 1.9 (still in alpha).

You can either use Clojure 1.9+, or use `taoensso.encore/boolean?` which does the same thing :-)

> Also it'd be helpful to have a link to a list of these kinds of functions that are available, couldn't find one (except for those in the examples).

Sure, that could be useful. Would guess that someone may have already compiled such a list, otherwise happy if you or someone else felt like adding a gist or wiki entry that we could link to from the README.

Cheers :-)

**Comment by daonsh** [comment]
Thanks.
I guess I won't compile one right now but will consider later...
Thanks again.

**Comment by ptaoussanis** [comment]
No problem :-)
